export const actionTypes = {
    SET_SINGEDUP_USERS: "SINGEDUP_USERS",
    SET_CURRENT_USER: "CURRENT_USER",
    SET_CURRENT_USERID: "SET_CURRENT_USERID",
    UPDATE_SIDEPANEL_STATE: "UPDATE_SIDEPANEL_STATE",
    SET_USER_POSTS: "SET_USER_POSTS",
};
